name: PyTest and build the docs - dev

on:
  workflow_dispatch:


jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Emacs
        run: sudo apt install emacs-nox --yes

      - name: Test and build
        run: .github/scripts/doc-builder.sh

      - name: Publish new docs
        uses: test-room-7/action-update-file@v1.6
        with:
          file-path: ./README.org
          commit-msg: "Update README"
          github-token: ${{ secrets.GITHUB_TOKEN }}
